// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  features:    Feature[];
  attribution: string;
  url:         string;
}

export interface Feature {
  type:       string;
  geometry:   Geometry;
  properties: Properties;
}

export interface Geometry {
  coordinates: number[];
  type:        string;
}

export interface Properties {
  name:            string;
  mapbox_id:       string;
  feature_type:    string;
  place_formatted: string;
  context:         Context;
  coordinates:     Coordinates;
  language:        string;
  maki:            string;
  external_ids:    ExternalIDS;
  metadata:        ExternalIDS;
}

export interface Context {
  country:      Country;
  region:       Region;
  postcode:     Postcode;
  district:     District;
  place:        District;
  locality:     District;
  neighborhood: District;
  street:       Postcode;
}

export interface Country {
  id:                   string;
  name:                 string;
  country_code:         string;
  country_code_alpha_3: string;
}

export interface District {
  id:   string;
  name: string;
}

export interface Postcode {
  name: string;
}

export interface Region {
  id:               string;
  name:             string;
  region_code:      string;
  region_code_full: string;
}

export interface Coordinates {
  latitude:  number;
  longitude: number;
  accuracy:  string;
}

export interface ExternalIDS {
}
